version: "3.9"

services:
  build-and-baraka-vitrine:
    image: buildbaraka-vitrine:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    restart: unless-stopped
    container_name: build-and-baraka-vitrine
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    read_only: true
    tmpfs:
      - /tmp
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
